
// Code generated by stanc fa623df
#include <stan/model/model_header.hpp>
namespace roaches2_model_namespace {


inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}

inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}


using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 

stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 15, column 2 to column 11)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 16, column 2 to column 17)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 19, column 3 to column 17)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 31, column 1 to column 19)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 33, column 2 to column 60)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 32, column 14 to line 34, column 2)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 32, column 1 to line 34, column 2)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 24, column 2 to column 22)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 25, column 2 to column 25)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 27, column 3 to column 27)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 26, column 2 to line 27, column 27)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 28, column 2 to column 35)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 2, column 2 to column 17)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 3, column 2 to column 17)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 4, column 9 to column 10)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 4, column 2 to column 22)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 5, column 9 to column 10)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 5, column 2 to column 19)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 6, column 9 to column 10)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 6, column 2 to column 19)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 7, column 9 to column 10)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 7, column 2 to column 22)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 8, column 8 to column 9)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 8, column 2 to column 11)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 11, column 9 to column 10)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 11, column 2 to column 21)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 12, column 2 to column 28)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 16, column 9 to column 10)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 19, column 10 to column 11)",
                                                      " (in '/Users/rob/.julia/dev/ParetoSmoothedImportanceSampling/examples/roaches/tmp/roaches2.stan', line 31, column 8 to column 9)"};



class roaches2_model final : public model_base_crtp<roaches2_model> {

 private:
  double lcm_sym37__;
  double lcm_sym36__;
  double lcm_sym35__;
  double lcm_sym34__;
  double lcm_sym33__;
  double lcm_sym32__;
  double lcm_sym31__;
  double lcm_sym30__;
  Eigen::Matrix<double, -1, 1> lcm_sym29__;
  int lcm_sym28__;
  int lcm_sym27__;
  int N;
  int K;
  Eigen::Matrix<double, -1, 1> exposure2;
  Eigen::Matrix<double, -1, 1> roach1;
  Eigen::Matrix<double, -1, 1> senior;
  Eigen::Matrix<double, -1, 1> treatment;
  std::vector<int> y;
  Eigen::Matrix<double, -1, 1> log_expo;
 
 public:
  ~roaches2_model() { }
  
  inline std::string model_name() const final { return "roaches2_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 fa623df", "stancflags = --warn-pedantic --O"};
  }
  
  
  roaches2_model(stan::io::var_context& context__,
                 unsigned int random_seed__ = 0,
                 std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "roaches2_model_namespace::roaches2_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      
      
      
      
      
      
      
      
      
      
      
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 13;
      context__.validate_dims("data initialization","N","int",
          context__.to_vec());
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 13;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 13;
      current_statement__ = 13;
      check_greater_or_equal(function__, "N", N, 0);
      current_statement__ = 14;
      context__.validate_dims("data initialization","K","int",
          context__.to_vec());
      K = std::numeric_limits<int>::min();
      
      current_statement__ = 14;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 14;
      current_statement__ = 14;
      check_greater_or_equal(function__, "K", K, 0);
      current_statement__ = 15;
      validate_non_negative_index("exposure2", "N", N);
      current_statement__ = 16;
      context__.validate_dims("data initialization","exposure2","double",
          context__.to_vec(N));
      exposure2 = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(exposure2, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<double> exposure2_flat__;
        current_statement__ = 16;
        assign(exposure2_flat__, nil_index_list(),
          context__.vals_r("exposure2"),
          "assigning variable exposure2_flat__");
        current_statement__ = 16;
        pos__ = 1;
        lcm_sym27__ = logical_gte(N, 1);
        if (lcm_sym27__) {
          current_statement__ = 16;
          assign(exposure2, cons_list(index_uni(1), nil_index_list()),
            exposure2_flat__[(1 - 1)], "assigning variable exposure2");
          current_statement__ = 16;
          pos__ = 2;
          for (int sym1__ = 2; sym1__ <= N; ++sym1__) {
            current_statement__ = 16;
            assign(exposure2, cons_list(index_uni(sym1__), nil_index_list()),
              exposure2_flat__[(pos__ - 1)], "assigning variable exposure2");
            current_statement__ = 16;
            pos__ = (pos__ + 1);}
        } 
      }
      current_statement__ = 17;
      validate_non_negative_index("roach1", "N", N);
      current_statement__ = 18;
      context__.validate_dims("data initialization","roach1","double",
          context__.to_vec(N));
      roach1 = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(roach1, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<double> roach1_flat__;
        current_statement__ = 18;
        assign(roach1_flat__, nil_index_list(), context__.vals_r("roach1"),
          "assigning variable roach1_flat__");
        current_statement__ = 18;
        pos__ = 1;
        current_statement__ = 18;
        if (lcm_sym27__) {
          current_statement__ = 18;
          assign(roach1, cons_list(index_uni(1), nil_index_list()),
            roach1_flat__[(1 - 1)], "assigning variable roach1");
          current_statement__ = 18;
          pos__ = 2;
          for (int sym1__ = 2; sym1__ <= N; ++sym1__) {
            current_statement__ = 18;
            assign(roach1, cons_list(index_uni(sym1__), nil_index_list()),
              roach1_flat__[(pos__ - 1)], "assigning variable roach1");
            current_statement__ = 18;
            pos__ = (pos__ + 1);}
        } 
      }
      current_statement__ = 19;
      validate_non_negative_index("senior", "N", N);
      current_statement__ = 20;
      context__.validate_dims("data initialization","senior","double",
          context__.to_vec(N));
      senior = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(senior, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<double> senior_flat__;
        current_statement__ = 20;
        assign(senior_flat__, nil_index_list(), context__.vals_r("senior"),
          "assigning variable senior_flat__");
        current_statement__ = 20;
        pos__ = 1;
        current_statement__ = 20;
        if (lcm_sym27__) {
          current_statement__ = 20;
          assign(senior, cons_list(index_uni(1), nil_index_list()),
            senior_flat__[(1 - 1)], "assigning variable senior");
          current_statement__ = 20;
          pos__ = 2;
          for (int sym1__ = 2; sym1__ <= N; ++sym1__) {
            current_statement__ = 20;
            assign(senior, cons_list(index_uni(sym1__), nil_index_list()),
              senior_flat__[(pos__ - 1)], "assigning variable senior");
            current_statement__ = 20;
            pos__ = (pos__ + 1);}
        } 
      }
      current_statement__ = 21;
      validate_non_negative_index("treatment", "N", N);
      current_statement__ = 22;
      context__.validate_dims("data initialization","treatment","double",
          context__.to_vec(N));
      treatment = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(treatment, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<double> treatment_flat__;
        current_statement__ = 22;
        assign(treatment_flat__, nil_index_list(),
          context__.vals_r("treatment"),
          "assigning variable treatment_flat__");
        current_statement__ = 22;
        pos__ = 1;
        current_statement__ = 22;
        if (lcm_sym27__) {
          current_statement__ = 22;
          assign(treatment, cons_list(index_uni(1), nil_index_list()),
            treatment_flat__[(1 - 1)], "assigning variable treatment");
          current_statement__ = 22;
          pos__ = 2;
          for (int sym1__ = 2; sym1__ <= N; ++sym1__) {
            current_statement__ = 22;
            assign(treatment, cons_list(index_uni(sym1__), nil_index_list()),
              treatment_flat__[(pos__ - 1)], "assigning variable treatment");
            current_statement__ = 22;
            pos__ = (pos__ + 1);}
        } 
      }
      current_statement__ = 23;
      validate_non_negative_index("y", "N", N);
      current_statement__ = 24;
      context__.validate_dims("data initialization","y","int",
          context__.to_vec(N));
      y = std::vector<int>(N, std::numeric_limits<int>::min());
      
      current_statement__ = 24;
      assign(y, nil_index_list(), context__.vals_i("y"),
        "assigning variable y");
      current_statement__ = 25;
      validate_non_negative_index("log_expo", "N", N);
      current_statement__ = 26;
      log_expo = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(log_expo, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 27;
      assign(log_expo, nil_index_list(), stan::math::log(exposure2),
        "assigning variable log_expo");
      current_statement__ = 28;
      validate_non_negative_index("beta", "K", K);
      current_statement__ = 29;
      validate_non_negative_index("eta", "N", N);
      current_statement__ = 30;
      validate_non_negative_index("log_lik", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += 1;
      num_params_r__ += K;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "roaches2_model_namespace::log_prob";
(void) function__;  // suppress unused var warning

    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      double lcm_sym26__;
      double lcm_sym25__;
      double lcm_sym24__;
      double lcm_sym23__;
      double lcm_sym22__;
      Eigen::Matrix<local_scalar_t__, -1, 1> lcm_sym21__;
      int lcm_sym20__;
      local_scalar_t__ phi;
      phi = DUMMY_VAR__;
      
      current_statement__ = 1;
      phi = in__.scalar();
      Eigen::Matrix<local_scalar_t__, -1, 1> beta;
      beta = Eigen::Matrix<local_scalar_t__, -1, 1>(K);
      stan::math::fill(beta, DUMMY_VAR__);
      
      current_statement__ = 2;
      beta = in__.vector(K);
      Eigen::Matrix<local_scalar_t__, -1, 1> eta;
      eta = Eigen::Matrix<local_scalar_t__, -1, 1>(N);
      stan::math::fill(eta, DUMMY_VAR__);
      
      assign(lcm_sym21__, nil_index_list(),
        add(
          add(
            add(add(stan::math::log(exposure2), beta[(1 - 1)]),
              multiply(beta[(2 - 1)], roach1)),
            multiply(beta[(3 - 1)], treatment)),
          multiply(beta[(4 - 1)], senior)), "assigning variable lcm_sym21__");
      assign(eta, nil_index_list(), lcm_sym21__, "assigning variable eta");
      {
        current_statement__ = 8;
        lp_accum__.add(normal_lpdf<propto__>(phi, 0, 10));
        current_statement__ = 9;
        lp_accum__.add(cauchy_lpdf<propto__>(beta[(1 - 1)], 0, 10));
        current_statement__ = 11;
        if (logical_gte(K, 2)) {
          current_statement__ = 10;
          lp_accum__.add(cauchy_lpdf<propto__>(beta[(2 - 1)], 0, 2.5));
          for (int i = 3; i <= K; ++i) {
            current_statement__ = 10;
            lp_accum__.add(cauchy_lpdf<propto__>(beta[(i - 1)], 0, 2.5));}
        } 
        current_statement__ = 12;
        lp_accum__.add(neg_binomial_2_log_lpmf<propto__>(y, lcm_sym21__, phi));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "roaches2_model_namespace::write_array";
(void) function__;  // suppress unused var warning

    (void) function__;  // suppress unused var warning

    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning

    
    try {
      double lcm_sym19__;
      double lcm_sym18__;
      double lcm_sym17__;
      double lcm_sym16__;
      double lcm_sym15__;
      double lcm_sym14__;
      double lcm_sym13__;
      double lcm_sym12__;
      Eigen::Matrix<local_scalar_t__, -1, 1> lcm_sym11__;
      int lcm_sym10__;
      int lcm_sym9__;
      int lcm_sym8__;
      int lcm_sym7__;
      double phi;
      phi = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      phi = in__.scalar();
      Eigen::Matrix<double, -1, 1> beta;
      beta = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(beta, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 2;
      beta = in__.vector(K);
      Eigen::Matrix<local_scalar_t__, -1, 1> eta;
      eta = Eigen::Matrix<local_scalar_t__, -1, 1>(N);
      stan::math::fill(eta, DUMMY_VAR__);
      
      vars__.emplace_back(phi);
      if (logical_gte(K, 1)) {
        vars__.emplace_back(beta[(1 - 1)]);
        for (int sym1__ = 2; sym1__ <= K; ++sym1__) {
          vars__.emplace_back(beta[(sym1__ - 1)]);}
      } 
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      assign(lcm_sym11__, nil_index_list(),
        add(
          add(
            add(add(stan::math::log(exposure2), beta[(1 - 1)]),
              multiply(beta[(2 - 1)], roach1)),
            multiply(beta[(3 - 1)], treatment)),
          multiply(beta[(4 - 1)], senior)), "assigning variable lcm_sym11__");
      assign(eta, nil_index_list(), lcm_sym11__, "assigning variable eta");
      if (emit_transformed_parameters__) {
        {
          lcm_sym8__ = logical_gte(N, 1);
          if (lcm_sym8__) {
            vars__.emplace_back(lcm_sym11__[(1 - 1)]);
            for (int sym1__ = 2; sym1__ <= N; ++sym1__) {
              vars__.emplace_back(lcm_sym11__[(sym1__ - 1)]);}
          } 
        }
      } else {
        lcm_sym8__ = logical_gte(N, 1);
      }
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      Eigen::Matrix<double, -1, 1> log_lik;
      log_lik = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(log_lik, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 7;
      if (lcm_sym8__) {
        current_statement__ = 5;
        assign(log_lik, cons_list(index_uni(1), nil_index_list()),
          neg_binomial_2_log_lpmf<false>(y[(1 - 1)], lcm_sym11__[(1 - 1)],
            phi), "assigning variable log_lik");
        for (int i = 2; i <= N; ++i) {
          current_statement__ = 5;
          assign(log_lik, cons_list(index_uni(i), nil_index_list()),
            neg_binomial_2_log_lpmf<false>(y[(i - 1)], lcm_sym11__[(i - 1)],
              phi), "assigning variable log_lik");}
      } 
      if (lcm_sym8__) {
        vars__.emplace_back(log_lik[(1 - 1)]);
        for (int sym1__ = 2; sym1__ <= N; ++sym1__) {
          vars__.emplace_back(log_lik[(sym1__ - 1)]);}
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      double lcm_sym6__;
      double lcm_sym5__;
      double lcm_sym4__;
      double lcm_sym3__;
      int lcm_sym2__;
      int lcm_sym1__;
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      double phi;
      phi = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      phi = context__.vals_r("phi")[(1 - 1)];
      Eigen::Matrix<double, -1, 1> beta;
      beta = Eigen::Matrix<double, -1, 1>(K);
      stan::math::fill(beta, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<double> beta_flat__;
        current_statement__ = 2;
        assign(beta_flat__, nil_index_list(), context__.vals_r("beta"),
          "assigning variable beta_flat__");
        current_statement__ = 2;
        pos__ = 1;
        lcm_sym1__ = logical_gte(K, 1);
        if (lcm_sym1__) {
          current_statement__ = 2;
          assign(beta, cons_list(index_uni(1), nil_index_list()),
            beta_flat__[(1 - 1)], "assigning variable beta");
          current_statement__ = 2;
          pos__ = 2;
          for (int sym1__ = 2; sym1__ <= K; ++sym1__) {
            current_statement__ = 2;
            assign(beta, cons_list(index_uni(sym1__), nil_index_list()),
              beta_flat__[(pos__ - 1)], "assigning variable beta");
            current_statement__ = 2;
            pos__ = (pos__ + 1);}
        } 
      }
      vars__.emplace_back(phi);
      if (lcm_sym1__) {
        vars__.emplace_back(beta[(1 - 1)]);
        for (int sym1__ = 2; sym1__ <= K; ++sym1__) {
          vars__.emplace_back(beta[(sym1__ - 1)]);}
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("phi");
    names__.emplace_back("beta");
    names__.emplace_back("eta");
    names__.emplace_back("log_lik");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(K)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N)});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "phi");
    for (int sym38__ = 1; sym38__ <= K; ++sym38__) {
      {
        param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym38__));
      }}
    if (emit_transformed_parameters__) {
      for (int sym38__ = 1; sym38__ <= N; ++sym38__) {
        {
          param_names__.emplace_back(std::string() + "eta" + '.' + std::to_string(sym38__));
        }}
    }
    
    if (emit_generated_quantities__) {
      for (int sym38__ = 1; sym38__ <= N; ++sym38__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym38__));
        }}
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "phi");
    for (int sym38__ = 1; sym38__ <= K; ++sym38__) {
      {
        param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym38__));
      }}
    if (emit_transformed_parameters__) {
      for (int sym38__ = 1; sym38__ <= N; ++sym38__) {
        {
          param_names__.emplace_back(std::string() + "eta" + '.' + std::to_string(sym38__));
        }}
    }
    
    if (emit_generated_quantities__) {
      for (int sym38__ = 1; sym38__ <= N; ++sym38__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym38__));
        }}
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"phi\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"parameters\"},{\"name\":\"eta\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"phi\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" << K << "},\"block\":\"parameters\"},{\"name\":\"eta\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  

    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        

};
}
using stan_model = roaches2_model_namespace::roaches2_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return roaches2_model_namespace::profiles__;
}

#endif


